export const TWBlurEffect =
  "backdrop-filter backdrop-blur-md bg-opacity-10  bg-background/85 dark:bg-background/60";
export const TWSideDrawerWidth = "250px";
export const TWSideDrawerAfterEffect =
  "after:transition-all after:duration-500 after:contents-[''] after:w-0 after:absolute after:left-0 after:h-0 after:bg-transparent after:rounded-tr-lg after:rounded-br-lg";
export const TWSideDrawerActiveAfterEffect =
  "text-primary hover:bg-primary/5 dark:hover:bg-primary/10 hover:text-primary dark:bg-primary/15 bg-primary/5 font-semibold after:w-[0.4rem] after:h-full after:bg-primary";

export const LocalStorageUserStore = "cozmo-gearz-user";

export const states = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

export const carriers = [
  "Aetna",
  "Alliant",
  "Ambetter",
  "AmeriHealth",
  "Anthem",
  "BCBS",
  "CareSource",
  "Christus",
  "Cigna",
  "Health Alliance",
  "HighMark",
  "Molina",
  "Oscar",
  "UHC",
];

export const carriers_with_tld_id = {
  Aetna: "14",
  Alliant: "194",
  Ambetter: "57",
  AmeriH: "225",
  Anthem: "20",
  AvMed: "",
  BCBS_AZ: "101",
  BCBS_IL: "45",
  BCBS_KS: "213",
  BCBS_MI: "30",
  BCBS_NE: "656",
  BCBS_OK: "31",
  BCBS_SC: "63",
  BCBS_TN: "242",
  BCBS_TX: "29",
  CareSource: "225",
  Christus: "193",
  Cigna: "19",
  HealthAlliance: "253",
  HighMark: "343",
  Molina: "73",
  Oscar: "158",
  UHC: "6",
};
